-- Esquema inicial do SIMA-SP (MySQL), a partir de bd_sima/MY_SQL_SCRIPT_SIMA_DB.sql.
--
-- Só a criação das tabelas: o CREATE DATABASE, o "use master", o DROP DATABASE e os INSERTs de
-- exemplo ficaram de fora (o banco é criado pela conexão e apagar banco em migration é perigoso).
-- Em banco que já existe, o Flyway faz baseline nesta versão e não roda este arquivo
-- (spring.flyway.baseline-on-migrate=true, baseline-version=1).

CREATE TABLE TBL_SENSOR
(
    ID_SENSOR               BIGINT          NOT NULL    PRIMARY KEY AUTO_INCREMENT,
    NR_LATITUDE             DECIMAL(9, 6)   NOT NULL,
    NR_LONGITUDE            DECIMAL(9, 6)   NOT NULL,
    TX_VIZINHANCA           VARCHAR(120)    NOT NULL,
    TX_STATUS_SENSOR        VARCHAR(20)     NOT NULL,
    DT_DATA_INSTALACAO      DATETIME(2)     NOT NULL    DEFAULT CURRENT_TIMESTAMP(2),

    CONSTRAINT CHK_STA_SEN                  CHECK (TX_STATUS_SENSOR IN ('ATIVO', 'INATIVO', 'MANUTENCAO')),
    CONSTRAINT CHK_SEN_LATITUDE_VALIDA      CHECK (NR_LATITUDE BETWEEN -90 AND 90),
    CONSTRAINT CHK_SEN_LONGITUDE_VALIDA     CHECK (NR_LONGITUDE BETWEEN -180 AND 180),
    CONSTRAINT UQ_LOCALIZACAO_SENSOR        UNIQUE (NR_LONGITUDE, NR_LATITUDE)
);

CREATE TABLE TBL_USUARIO
(
    ID_USUARIO                  BIGINT          NOT NULL    PRIMARY KEY AUTO_INCREMENT,
    TX_EMAIL                    VARCHAR(80)     NOT NULL,
    TX_SENHA_HASH               VARCHAR(255)    NOT NULL,
    NR_LATITUDE                 DECIMAL(9, 6)   NOT NULL,
    NR_LONGITUDE                DECIMAL(9, 6)   NOT NULL,
    TX_PERMISSAO_LOCALIZACAO    VARCHAR(3)      NOT NULL,
    TX_PERMISSAO_ALERTA         VARCHAR(3)      NOT NULL,
    TX_TIPO_USUARIO             VARCHAR(20)     NOT NULL,

    CONSTRAINT UQ_EMAIL                     UNIQUE (TX_EMAIL),
    CONSTRAINT CHK_PER_LOC                  CHECK (TX_PERMISSAO_LOCALIZACAO IN ('SIM', 'NAO')),
    CONSTRAINT CHK_PER_ALE                  CHECK (TX_PERMISSAO_ALERTA IN ('SIM', 'NAO')),
    CONSTRAINT CHK_TIP_USU                  CHECK (TX_TIPO_USUARIO IN ('ADMIN', 'ANALISTA', 'DEFESA_CIVIL', 'CIDADAO')),
    CONSTRAINT CHK_USU_LATITUDE_VALIDA      CHECK (NR_LATITUDE BETWEEN -90 AND 90),
    CONSTRAINT CHK_USU_LONGITUDE_VALIDA     CHECK (NR_LONGITUDE BETWEEN -180 AND 180)
);

CREATE TABLE TBL_LEITURA
(
    ID_LEITURA                      BIGINT          NOT NULL    PRIMARY KEY AUTO_INCREMENT,
    ID_SENSOR                       BIGINT          NOT NULL,
    NR_NIVEL_AGUA                   FLOAT           NOT NULL,
    NR_PORCENTAGEM_DESPERDICIO      FLOAT           NOT NULL,
    NR_CHUVA_MM                     FLOAT           NOT NULL,
    DT_DATA_LEITURA                 DATETIME(2)     NOT NULL    DEFAULT CURRENT_TIMESTAMP(2),
    TX_NIVEL_RISCO                  VARCHAR(20)     NOT NULL,
    NR_PROBABILIDADE_ALAGAMENTO     FLOAT           NOT NULL,
    TX_PREVISAO_NIVEL_RISCO         VARCHAR(20)     NOT NULL,

    CONSTRAINT SEN_FK_LEI                   FOREIGN KEY (ID_SENSOR) REFERENCES TBL_SENSOR (ID_SENSOR),
    CONSTRAINT CHK_RISCO                    CHECK (TX_NIVEL_RISCO IN ('BAIXO', 'MEDIO', 'ALTO', 'CRITICO')),
    CONSTRAINT CK_NIVEL_AGUA                CHECK (NR_NIVEL_AGUA >= 0),
    CONSTRAINT CK_PORCENTAGEM_DESPERDICIO   CHECK (NR_PORCENTAGEM_DESPERDICIO >= 0),
    CONSTRAINT CK_CHUVA_MM                  CHECK (NR_CHUVA_MM >= 0),
    CONSTRAINT CK_PROBABILIDADE_ALAGAMENTO  CHECK (NR_PROBABILIDADE_ALAGAMENTO >= 0)
);

CREATE INDEX IDX_LEI_SENSOR_DATA ON TBL_LEITURA (ID_SENSOR, DT_DATA_LEITURA DESC);

CREATE TABLE TBL_ALERTA
(
    ID_ALERTA           BIGINT          NOT NULL    PRIMARY KEY AUTO_INCREMENT,
    ID_LEITURA          BIGINT          NOT NULL,
    TX_MENSAGEM         VARCHAR(255)    NOT NULL,
    TX_STATUS           VARCHAR(20)     NOT NULL,
    DT_DATA_ALERTA      DATETIME(2)     NOT NULL    DEFAULT CURRENT_TIMESTAMP(2),

    CONSTRAINT LEI_FK_ALE                   FOREIGN KEY (ID_LEITURA) REFERENCES TBL_LEITURA (ID_LEITURA),
    CONSTRAINT CHK_STATUS                   CHECK (TX_STATUS IN ('ATIVO', 'RESOLVIDO'))
);
